# Generated by Django 2.2.4 on 2021-08-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_orderproduct_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart_total',
        ),
    ]
